language: python
python:
  - 3.11

    # Write install command after writing requirements.md file
install: 
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')" 

script: 
  - pwd
  - pytest test
  
name: Python Syntax Checker
uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

notifications:
  email:
    recipients: 
      - abhujba@ncsu.edu
      - aakore@ncsu.edu
      - srpate27@ncsu.edu
      - yhasabe@ncsu.edu
    
    on_success: always
    on_failure: always
    
   
