language: python
python:
  - 3.6

    # Write install command after writing requirements.md file
install: 
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')" 

script: 
  - pwd
  - python sentimental_analysis/realworld/functional_testing.py
  
name: Python Syntax Checker
uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

notifications:
  email:
    recipients: 
      - ajoshi23@ncsu.edu
      - mrpudlo@ncsu.edu
      - magavade@ncsu.edu
      - sjain26@ncsu.edu
      - pyadla22@ncsu.edu
    
    on_success: never
    on_failure: always
    
   
