name: Code Formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Black
      run: |
        pip install black
    - name: Check code formatting
      run: |
        black . --diff --exclude '/(black-master|assests|test|pycodestyle-master|.*/test/.*\.py)/'
      continue-on-error: true
